// src/utils/content.js

export const PARK_BENCH_QUOTES = [
  "You do not have to have a single productive thought right now.",
  "The world will keep spinning if you close your eyes for two minutes.",
  "Notice the silence underneath the noise.",
  "You are allowed to just exist today.",
  "Rest is not a reward. It is a necessity.",
  "Some days move slowly. That is okay.",
  "A quiet moment can change the rhythm of a day.",
  "Not every thought needs an answer.",
  "A pause can be enough for now.",
  "Silence sometimes says what words cannot.",
  "The mind often softens when it rests.",
  "This moment does not need to be solved.",
  "A few calm breaths can shift the day.",
  "Stillness can appear in simple moments.",
  "Even busy days contain small pauses.",
  "Nothing urgent is required from this moment.",
  "A gentle breath can begin again.",
  "Quiet moments often arrive unnoticed.",
  "The mind can rest for a while.",
  "Some thoughts pass when given space.",
  "A calm moment is never wasted.",
  "The day can unfold at its own pace.",
  "A pause can bring a different perspective.",
  "This moment can simply exist.",
  "Breathing slowly often changes the mood.",
  "Not every moment needs improvement.",
  "Sometimes a pause is the answer.",
  "A quiet breath can be enough.",
  "Stillness often hides in ordinary moments.",
  "The day can continue gently from here.",
  "A calm mind does not rush.",
  "Small pauses can carry quiet strength.",
  "The present moment can hold its own balance.",
  "The mind can soften with patience.",
  "Even brief silence can refresh the mind.",
  "Nothing needs to be rushed right now.",
  "A quiet pause often brings clarity.",
  "The mind sometimes settles on its own.",
  "The present moment asks very little.",
  "A slow breath can create space.",
  "Calm moments are often simple.",
  "Silence can carry gentle comfort.",
  "Even a short pause can help.",
  "Thoughts may fade when left alone.",
  "A moment of stillness can be enough.",
  "Calm often appears when nothing is forced.",
  "This moment does not require judgment.",
  "Some thoughts simply come and go.",
  "Nothing urgent needs to happen here.",
  "Stillness can live inside ordinary time.",
  "Even a single breath matters.",
  "Silence often carries peace.",
  "Calm can appear in small breaths.",
  "The mind can settle quietly.",
  "Even a short pause has value.",
  "Silence may soften the day.",
  "Thoughts may fade naturally.",
  "This moment can simply be.",
  "आराम करना कोई इनाम नहीं है। यह आपकी ज़रूरत है।",
  "कुछ दिन धीमी गति से गुज़रते हैं। यह ठीक है।",
  "हर विचार का उत्तर देना आवश्यक नहीं है।",
  "यह पल बस ऐसे ही अस्तित्व में रह सकता है।",
  "मन को कभी-कभी बस एक ठहराव की ज़रूरत होती है।",
  "शांति अक्सर खामोशी से आती है।",
  "एक शांत पल आपका अपना है।",
  "वर्तमान क्षण पहले से ही यहाँ है।",
  "कुछ विचार अपने आप गुज़र जाते हैं।",
  "बिना जल्दी के, बस यहाँ रहें।",
  "मन को थोड़ा विश्राम दें।",
  "इस पल में कुछ सुलझाना ज़रूरी नहीं।",
  "एक धीमी सांस काफी हो सकती है।",
  "शांति को खोजने की ज़रूरत नहीं — वह पहले से यहाँ है।",
];

export const MEDITATIONS = [
  { id:1,  title:"Morning Light",     titleH:"सुबह की रोशनी",   dur:5,  cat:"Morning",    catH:"सुबह",       emoji:"🌄", desc:"Greet the day with warmth and intention.",              descH:"गर्माहट और इरादे के साथ दिन का स्वागत करें।",      col:"#f0c080" },
  { id:2,  title:"Heavy Heart",       titleH:"भारी दिल",         dur:4,  cat:"Calm",       catH:"शांति",      emoji:"🫶", desc:"Hold yourself gently through difficult feelings.",      descH:"कठिन भावनाओं में खुद को धीरे से थामें।",            col:"#d4806a" },
  { id:3,  title:"Earth Rest",        titleH:"धरती का आराम",     dur:10, cat:"Relaxation", catH:"विश्राम",    emoji:"🌿", desc:"Feel rooted and at ease from head to toe.",             descH:"सिर से पाँव तक जड़ें और सुकून महसूस करें।",         col:"#8aaa7a" },
  { id:4,  title:"Loving Kindness",   titleH:"प्रेम और करुणा",   dur:8,  cat:"Heart",      catH:"हृदय",       emoji:"🕯️", desc:"Soften toward yourself and the world around you.",      descH:"खुद और दुनिया के प्रति नरम हों।",                   col:"#d4845a" },
  { id:5,  title:"Drifting to Sleep", titleH:"नींद की ओर",        dur:15, cat:"Sleep",      catH:"नींद",       emoji:"🌙", desc:"Let go of the day and sink into rest.",                 descH:"दिन को जाने दें और आराम में डूब जाएं।",             col:"#8899cc" },
  { id:6,  title:"Quick Return",      titleH:"त्वरित वापसी",      dur:2,  cat:"Urgent",     catH:"तत्काल",     emoji:"🌱", desc:"Come back to earth. Right here, right now.",            descH:"वापस आएं। ठीक यहाँ, ठीक अभी।",                     col:"#8aaa7a" },
  { id:7,  title:"Still Water",       titleH:"शांत जल",           dur:6,  cat:"Calm",       catH:"शांति",      emoji:"💧", desc:"Watch your thoughts pass like ripples on still water.", descH:"विचारों को शांत पानी की लहरों की तरह गुज़रते देखें।", col:"#5D93C4" },
  { id:8,  title:"Forest Walk",       titleH:"जंगल की सैर",       dur:12, cat:"Relaxation", catH:"विश्राम",    emoji:"🌲", desc:"A slow wander through a forest that holds no demands.", descH:"एक जंगल में धीमी सैर — बिना किसी माँग के।",         col:"#6B765F" },
  { id:9,  title:"Heart Warmth",      titleH:"दिल की गर्माहट",    dur:5,  cat:"Heart",      catH:"हृदय",       emoji:"☀️", desc:"A short practice of warmth for yourself and others.",   descH:"खुद और दूसरों के लिए गर्माहट का एक छोटा अभ्यास।",  col:"#D4A373" },
  { id:10, title:"Nightly Release",   titleH:"रात का विसर्जन",     dur:10, cat:"Sleep",      catH:"नींद",       emoji:"🌌", desc:"Gently dissolve the weight of the day.",                descH:"दिन का बोझ धीरे से घुलने दें।",                     col:"#726FBA" },
  { id:11, title:"Breath Anchor",     titleH:"सांस का लंगर",      dur:3,  cat:"Morning",    catH:"सुबह",       emoji:"⚓", desc:"Three minutes of settled breath to start your day.",    descH:"दिन की शुरुआत के लिए तीन मिनट की स्थिर सांस।",    col:"#7A9EA8" },
  { id:12, title:"Compassion Rain",   titleH:"करुणा की बारिश",    dur:7,  cat:"Heart",      catH:"हृदय",       emoji:"🌧️", desc:"Let compassion fall on every part of yourself.",        descH:"खुद के हर हिस्से पर करुणा को बरसने दें।",           col:"#9B3D4F" },
];

export const BREATHE_PATTERNS = [
  { name:"Anchor",     inhale:4, hold1:2, exhale:6, hold2:0, desc:"4-2-6 · Daily calm" },
  { name:"Box Breathing", inhale:4, hold1:4, exhale:4, hold2:4, desc:"4-4-4-4 · Used by soldiers to calm the mind instantly", bold:true },
  { name:"Deep Sleep", inhale:4, hold1:7, exhale:8, hold2:0, desc:"4-7-8 · Rest & release" },
  { name:"Vitality",   inhale:6, hold1:0, exhale:2, hold2:0, desc:"6-0-2 · Awaken" },
];

export const PROMPTS = [
  // ── JSukoon originals — English ──
  "What would sukoon feel like in your body right now, if it were allowed in?",
  "Name one thing that happened today that nobody knows about. How did it sit with you?",
  "What are you performing for the world that exhausts you the most?",
  "If your mind had a weather forecast today, what would it be?",
  "What have you been meaning to forgive yourself for?",
  "Where in your life are you being loud when you want to be still?",
  "What does the tired part of you need that the busy part keeps ignoring?",
  "If you could send a message to yourself three years ago, what would it say?",
  "What feeling have you been swallowing today?",
  "When was the last time you felt genuinely at ease? What was different then?",
  "What would you do differently today if nobody was watching or judging?",
  "What is the one thought that returns again and again this week?",
  "Describe this moment — the temperature, the light, the feeling — in three lines.",
  "What are you holding onto that once made sense but no longer does?",
  "Who in your life makes you feel most like yourself? Why haven't you called them?",
  "What does your body know that your mind is still arguing with?",
  "Write one sentence about today that is completely, uncomplicatedly true.",
  "What boundary would bring you the most relief to set?",
  "If sukoon is a destination, what is the distance between you and it right now?",
  "What noise — inside or outside — do you most want silence from today?",
  // ── JSukoon originals — Hindi ──
  "अगर आपका मन आज बोल सकता, तो वह क्या कहता?",
  "आज आपने क्या महसूस किया जो आपने किसी को नहीं बताया?",
  "इस हफ्ते आप क्या भूल गए जो याद रखना ज़रूरी था?",
  "जो थकान आप महसूस कर रहे हैं — वह शरीर की है या मन की?",
  "आज का एक पल जो बिल्कुल शांत था — वह कब था?",
];

export const MOODS = [
  { emoji:"😶‍🌫️", label:"Numb",       labelH:"सुन्न",       val:1  },
  { emoji:"😔",   label:"Heavy",      labelH:"भारी",        val:2  },
  { emoji:"😟",   label:"Anxious",    labelH:"चिंतित",      val:3  },
  { emoji:"😤",   label:"Frustrated", labelH:"परेशान",      val:4  },
  { emoji:"😪",   label:"Exhausted",  labelH:"थका हुआ",     val:5  },
  { emoji:"😐",   label:"Unsettled",  labelH:"बेचैन",       val:6  },
  { emoji:"😌",   label:"Quiet",      labelH:"शांत",        val:7  },
  { emoji:"🙂",   label:"Okay",       labelH:"ठीक हूँ",     val:8  },
  { emoji:"🤍",   label:"Gentle",     labelH:"कोमल",        val:9  },
  { emoji:"😊",   label:"Warm",       labelH:"गर्म",        val:10 },
  { emoji:"✨",   label:"Grateful",   labelH:"कृतज्ञ",      val:11 },
  { emoji:"☀️",   label:"Radiant",    labelH:"प्रकाशमान",   val:12 },
];

export const ENERGY_STATES = [
  { key:"Racing Thoughts", short:"Chatter",   hi:"बकबक" },
  { key:"Restless Mind",   short:"Restless",  hi:"बेचैन" },
  { key:"Overwhelmed",     short:"Dazed",     hi:"अभिभूत" },
  { key:"Heavy Thoughts",  short:"Heavy",     hi:"भारी" },
  { key:"Tired Mind",      short:"Tired",     hi:"थका" },
  { key:"Need Quiet",      short:"Noise",     hi:"शोर" },
];

export const SOUNDS = [
  { name:"Birds",  hi:"पक्षी",  file:"birds.mp3"  },
  { name:"Flute",  hi:"बांसुरी",file:"flute.mp3"  },
  { name:"Forest", hi:"जंगल",   file:"forest.mp3" },
  { name:"Waves",  hi:"लहरें",  file:"waves.mp3"  },
  { name:"Wind",   hi:"हवा",    file:"wind.mp3"   },
];

export const MILESTONES = [
  { label:"First step",       labelH:"पहला कदम",          needSessions:1,   needStreak:0,  emoji:"🌱" },
  { label:"3-day warmth",     labelH:"3 दिन की देखभाल",    needSessions:0,   needStreak:3,  emoji:"🌿" },
  { label:"10 sessions",      labelH:"10 सत्र",            needSessions:10,  needStreak:0,  emoji:"🕯️" },
  { label:"Week of care",     labelH:"देखभाल का सप्ताह",   needSessions:0,   needStreak:7,  emoji:"🌻" },
  { label:"30 sessions",      labelH:"30 सत्र",            needSessions:30,  needStreak:0,  emoji:"🏵️" },
  { label:"50 sessions",      labelH:"50 सत्र",            needSessions:50,  needStreak:0,  emoji:"🌙" },
  { label:"30-day streak",    labelH:"30 दिन की लकीर",     needSessions:0,   needStreak:30, emoji:"⭐" },
  { label:"100 sessions",     labelH:"100 सत्र",           needSessions:100, needStreak:0,  emoji:"💎" },
  { label:"3-month streak",   labelH:"3 महीने की लकीर",    needSessions:0,   needStreak:90, emoji:"🌟" },
  { label:"365 sessions",     labelH:"365 सत्र",           needSessions:365, needStreak:0,  emoji:"🌞" },
  { label:"Year of care",     labelH:"देखभाल का एक साल",   needSessions:0,   needStreak:365,emoji:"🪷" },
  { label:"500 sessions",     labelH:"500 सत्र",           needSessions:500, needStreak:0,  emoji:"🔮" },
  { label:"1000 sessions",    labelH:"1000 सत्र",          needSessions:1000,needStreak:0,  emoji:"✨" },
  { label:"1000-day streak",  labelH:"1000 दिन की लकीर",   needSessions:0,   needStreak:1000,emoji:"🌌" },
];

export const CRISIS_WORDS = [
  // ── Self-harm / suicide – English ──
  "suicide","suicidal","kill myself","end my life","want to die","wanna die","wish i was dead",
  "wish i were dead","don't want to live","dont want to live","no reason to live","not worth living",
  "life is not worth","better off dead","better off without me","everyone would be better",
  "tired of living","tired of life","end it all","end it","end everything","end my pain",
  "take my own life","take my life","hurt myself","harm myself","self harm","self-harm","selfharm",
  "cut myself","cutting myself","burn myself","starve myself","injure myself",
  "hang myself","hanging myself","jump off","jump from","overdose","od myself",
  "pills to die","bleed out","slit my wrists","slit my throat","shoot myself",
  "drown myself","suffocate myself","no point anymore","nothing left to live for",
  "can't go on","cannot go on","done with life","done with everything","give up on life",
  "check out permanently","permanent solution","disappear forever","never wake up",
  "go to sleep forever","not wake up","dark thoughts","intrusive thoughts of death",
  // ── Harming others – English ──
  "kill someone","kill him","kill her","kill them","want to kill","going to kill",
  "murder someone","murder him","murder her","want to murder","planning to kill",
  "hurt someone","hurt him","hurt her","hurt them badly","make them suffer",
  "attack someone","stab someone","shoot someone","poison someone",
  "make them pay","they deserve to die","want them dead","hope they die",
  "i will hurt","i will harm","i will attack","i want revenge","take revenge",
  // ── Hindi / Urdu / Hinglish ──
  "mar jana","mar jaunga","mar jaungi","mar jaana","marna chahta","marna chahti",
  "marna chahta hoon","marna chahti hoon","jeene ka man nahi","jeene ki ichha nahi",
  "jaan de dunga","jaan de dungi","jaan dena chahta","khudkushi","khud ko marna",
  "aatmahatya","aatm hatya","atmhatya","khud ko khatam","khud ko hurt karna",
  "zindagi khatam","zindagi se thak","jeena nahi","jeena nahi chahta","jeena nahi chahti",
  "mujhe nahi jeena","main mar jaunga","main mar jaungi","nas kaat","naas kaat",
  "neend nahi uthna","neend mein mar","hamesha so jana","so jana forever",
  "sab khatam karna","sab khatam kar dunga","apni jaan lena","apni jaan lunga",
  "dard khatam karna","dard se mukti","is duniya se jaana","duniya chhod dena",
  "kisi ko marna","usse marna","usko khatam karna","kisi ko hurt karna",
  "inhe marna chahta","inhe mar dunga","badla lena","badla lunga",
  // ── Urdu script ──
  "خودکشی","مرنا چاہتا","جان دینا","ختم کرنا","تھک گیا زندگی سے",
];

export const CRISIS_RESOURCES = [
  { name:"AASRA",                  number:"9820466627",   desc:"24/7 crisis support" },
  { name:"Vandrevala Foundation",  number:"1860-2662-345",desc:"24/7 free helpline" },
  { name:"iCall (India)",          number:"9152987821",   desc:"Mon–Sat, 8am–10pm" },
];