import React from 'react';
import { PageNav } from '../../components/SharedUI';

export function LegalDisclaimer({ setTab, goBack, T, lang }) {
  const hi = lang === "Hindi";

  // Hardcoded here so the legal page never breaks if constants change
  const CRISIS_RESOURCES = [
    { name: "KIRAN (Mental Health)", desc: "24/7 Govt. Helpline", number: "18005990019" },
    { name: "AASRA (Crisis Support)", desc: "Professional Counseling", number: "9820466726" },
    { name: "Emergency", desc: "National Emergency", number: "112" }
  ];

  const Section = ({ num, title, color, children }) => (
    <div style={{ marginBottom: 28 }}>
      <h3 style={{ color: color || T.text, fontSize: 13, fontWeight: 600, letterSpacing: 1, textTransform: "uppercase", marginBottom: 10 }}>
        {num}. {title}
      </h3>
      {children}
    </div>
  );

  const P = ({ children, style }) => (
    <p style={{ fontSize: 13, lineHeight: 1.95, color: T.textSoft, marginBottom: 8, ...style }}>
      {children}
    </p>
  );

  return (
    <div style={{ height: "100%", display: "flex", flexDirection: "column", background: T.bg, overflow: "hidden" }}>
      <PageNav onBack={goBack || (() => setTab("home"))} onHome={() => setTab("home")} backLabel={hi ? "वापस" : "Back"} T={T} lang={lang} />
      
      <div className="scroll-area fade-up" style={{ flex: 1, overflowY: "auto", padding: "0 0 60px" }}>
        <div style={{ padding: "0 18px 100px" }}>
          
          <h1 style={{ fontFamily: "'Cormorant Garamond',serif", fontSize: 26, color: T.text, marginBottom: 4, marginTop: 16 }}>
            Legal Disclaimer
          </h1>
          <p style={{ fontSize: 11, color: T.muted, marginBottom: 6, letterSpacing: .5 }}>
            Last updated: March 2026
          </p>
          
          {/* THE RED FORTRESS - Absolute Emergency Disclaimer */}
          <div style={{ background: "rgba(224,102,102,0.07)", border: "2px solid rgba(224,102,102,0.35)", borderRadius: 18, padding: "18px 20px", marginBottom: 32, marginTop: 24 }}>
            <p style={{ fontSize: 11, color: "#e06666", letterSpacing: 2, textTransform: "uppercase", marginBottom: 10, fontWeight: 600 }}>
              ⚠ IMPORTANT — READ FIRST
            </p>
            <p style={{ fontSize: 13, lineHeight: 1.9, color: "rgba(255,180,180,0.85)", marginBottom: 10 }}>
              JSukoon is <strong style={{ color: "#ff8080" }}>not a crisis intervention service</strong>. It does not provide therapy, counselling, psychiatric diagnosis, or emergency medical support.
            </p>
            <p style={{ fontSize: 13, lineHeight: 1.9, color: "rgba(255,180,180,0.85)", marginBottom: 10 }}>
              If you are experiencing thoughts of self-harm, suicide, or severe psychological distress — <strong style={{ color: "#ff8080" }}>stop using this app immediately</strong> and contact a professional at one of the following numbers:
            </p>
            {CRISIS_RESOURCES.map(r => (
              <a key={r.name} href={`tel:${r.number}`} style={{ textDecoration: "none", display: "flex", justifyContent: "space-between", alignItems: "center", padding: "10px 0", borderBottom: "1px solid rgba(224,102,102,0.15)" }}>
                <div>
                  <p style={{ fontSize: 13, fontWeight: 600, color: "#ff8080", margin: 0 }}>{r.name}</p>
                  <p style={{ fontSize: 13, color: "rgba(255,150,150,0.75)", margin: 0 }}>{r.desc}</p>
                </div>
                <p style={{ fontSize: 15, fontWeight: 700, color: "#ff6b6b", margin: 0 }}>{r.number}</p>
              </a>
            ))}
          </div>

          <div style={{ fontSize: 13, lineHeight: 1.9, color: T.textSoft }}>
            <p style={{ color: T.accent, fontWeight: 600, fontSize: 13, marginBottom: 24, letterSpacing: 1, textTransform: "uppercase" }}>
              JSukoon — Full Terms
            </p>

            <Section num="1" title="Nature of the App" color={T.text}>
              <P>JSukoon is a general-purpose digital wellbeing application offering guided exercises, journaling prompts, and reflective content.</P>
              <P>It is entirely self-guided and is not a medical device, nor is it a substitute for licensed professional mental health care.</P>
            </Section>

            <Section num="2" title="Artificial Intelligence (AI) Notice" color={T.text}>
              <P>Certain interactive features within JSukoon, including reflective responses, are powered by Artificial Intelligence (AI) algorithms.</P>
              <P>These responses are generated by a machine, not a human. AI can hallucinate, lack context, and provide inaccurate or inappropriate information. You agree to never use AI-generated responses as a basis for personal, medical, legal, or life decisions.</P>
            </Section>

            <Section num="3" title="Data & Privacy Responsibility" color={T.text}>
              <P>JSukoon stores your personal journal entries, mood logs, reflections, and session data securely on Supabase — a trusted cloud platform protected by row-level security and encrypted connections.</P>
              <P>While we take every precaution to protect your data, no method of internet transmission is 100% secure. The developer is not responsible for any data loss or breaches resulting from circumstances beyond our reasonable control. You are responsible for keeping your login credentials secure.</P>
            </Section>

            <Section num="4" title="Limitation of Liability" color={T.text}>
              <P>To the maximum extent permitted by applicable law, the developer of JSukoon disclaims all liability for any direct, indirect, incidental, or consequential damages arising out of your use or inability to use this application.</P>
              <P>You agree to use this application strictly at your own risk. The app makes no warranty regarding any outcome, including emotional improvement or stress reduction.</P>
            </Section>

            <div style={{ height: 1, background: T.borderWarm, margin: "32px 0" }} />

            <p style={{ color: T.accent, fontWeight: 600, fontSize: 11, textTransform: "uppercase", letterSpacing: 1.5, marginBottom: 16 }}>
              Plain Language Summary
            </p>
            <div style={{ textAlign: "center", fontStyle: "italic", fontSize: 14, lineHeight: 2.4, color: T.muted, fontFamily: "'Cormorant Garamond',serif" }}>
              <p>JSukoon listens, but does not diagnose.</p>
              <p>It reflects, but does not advise.</p>
              <p>It offers space, not treatment.</p>
              <p>For real help, please call a real person.</p>
            </div>
          </div>
          
        </div>
      </div>
    </div>
  );
}